### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [rtlarose/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:
Robert, congrats on finishing the Dasmoto project! You did an excellent job making your files readable as you commented your HTML file throughout although next time consider adding comments to your CSS file as well. 

One thing to keep in mind is reducing duplicate CSS rules. I noticed that you applied the following styles to three different sections (paint, frames, brushes)
```CSS
font-size: 32px;
font-weight: bold;
color: white;
```

Instead of repeating this code three different times it would have been more efficient to do the following:
```CSS
.brushes h2 {
    background-color: mediumspringgreen;
}

.frames h2 {
    background-color: lightcoral;
}

.paint h2 {
    background-color: skyblue;
}

h2 {
    font-size: 32px;
    font-weight: bold;
    color: white;
}
```

This way you only write the style they all share once which makes it easier for example to maintain the project down the road.
